# Generated by Django 5.2 on 2026-02-24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LobbyRoom",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("creator_wallet", models.CharField(db_index=True, max_length=42)),
                ("opponent_wallet", models.CharField(blank=True, db_index=True, max_length=42, null=True)),
                ("wager_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("started", "Started"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("contract_game_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SwapRecord",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("from_token", models.CharField(max_length=42)),
                ("to_token", models.CharField(max_length=42)),
                ("from_amount", models.CharField(max_length=100)),
                ("to_amount_estimate", models.CharField(max_length=100)),
                ("volume_usd", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("tx_hash", models.CharField(blank=True, max_length=80, null=True)),
                ("oneinch_response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="YieldRecord",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("principal_wei", models.CharField(max_length=100)),
                ("apr_bps", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField(default=30)),
                ("estimated_yield_wei", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
