from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, HttpUrl


class PlatformEnum(str, Enum):
    craigslist = "craigslist"
    mercari = "mercari"
    nextdoor = "nextdoor"
    offerup = "offerup"
    etsy = "etsy"
    poshmark = "poshmark"
    shopify = "shopify"
    custom = "custom"


class SellerPreference(BaseModel):
    tone: Optional[str] = Field(
        None,
        description="Preferred copy tone (e.g., premium, playful, concise)",
    )
    min_price: Optional[float] = Field(
        None,
        description="Lowest acceptable price for auto-negotiation guardrails",
    )
    target_price: Optional[float] = Field(
        None,
        description="Ideal listing price suggested to pricing agent",
    )
    pickup_only: Optional[bool] = Field(
        False, description="If true, restrict listings to local pickup"
    )


class ListingAsset(BaseModel):
    source_uri: Optional[HttpUrl] = Field(
        None, description="Publicly accessible URL for the uploaded asset."
    )
    base64_payload: Optional[str] = Field(
        None,
        description="Optional base64 encoded asset body when direct upload is used.",
    )
    caption: Optional[str] = Field(None, description="User-provided caption or note.")


class ListingRequest(BaseModel):
    listing_type: Optional[str] = Field(
        "item",
        description="High-level listing type: item | event | service (used for copy structure).",
    )
    title_hint: Optional[str] = Field(
        None, description="Optional working title supplied by the seller."
    )
    raw_description: str = Field(
        ..., description="Free-form notes describing the item, condition, and story."
    )
    brand: Optional[str] = Field(None, description="Optional brand/designer/organizer name.")
    condition: Optional[str] = Field(
        None, description="Condition summary (e.g., new, like new, good, fair)."
    )
    dimensions: Optional[str] = Field(
        None,
        description="Optional dimensions (e.g., 48x24x18 in) for items; keep human-readable.",
    )
    delivery: Optional[str] = Field(
        None,
        description="Fulfillment hint: local pickup | shipping | delivery | digital.",
    )
    event_datetime: Optional[str] = Field(
        None, description="For events: ISO-ish datetime string (e.g., 2025-12-20 19:00)."
    )
    event_duration: Optional[str] = Field(
        None, description="For events: human duration (e.g., 2 hours)."
    )
    category: Optional[str] = Field(
        None, description="High-level category to help routing (e.g., furniture)."
    )
    location: Optional[str] = Field(
        None, description="City/region for localized marketplaces."
    )
    assets: List[ListingAsset] = Field(
        default_factory=list, description="Collection of reference photos/videos."
    )
    target_platforms: List[PlatformEnum] = Field(
        default_factory=lambda: [PlatformEnum.craigslist],
        description="Marketplaces that should receive this listing.",
    )
    preferences: SellerPreference = Field(
        default_factory=SellerPreference,
        description="Preferences controlling tone, pricing, negotiations.",
    )


class ListingStatus(BaseModel):
    listing_id: str = Field(..., description="Internal tracking identifier.")
    state: str = Field(
        ...,
        description="State machine stage (ingesting, enhancing, drafting, publishing, live, closed).",
    )
    platforms_live: List[PlatformEnum] = Field(
        default_factory=list, description="Platforms with confirmed publication."
    )
    notes: Optional[str] = Field(None, description="Additional context for the seller.")


class ListingResponse(BaseModel):
    status: ListingStatus
    recommended_price: Optional[float] = Field(
        None, description="Initial suggestion from valuation pipeline."
    )
    title_options: List[str] = Field(
        default_factory=list,
        description="Candidate title options generated by the copy pipeline.",
    )
    selected_title: Optional[str] = Field(
        None,
        description="Selected title to use for posting (can be overridden per platform).",
    )
    preview_description: Optional[str] = Field(
        None, description="First-pass marketing copy preview."
    )
    platform_variants: dict[str, str] = Field(
        default_factory=dict,
        description="Per-platform description variants keyed by platform id.",
    )
    platform_publication: dict[str, dict] = Field(
        default_factory=dict,
        description="Per-platform publication status and posting packages (if available).",
    )
    verified_attributes: dict[str, str] = Field(
        default_factory=dict,
        description="High-confidence attributes inferred from images/notes via redundant verification.",
    )
    perception_report: dict = Field(
        default_factory=dict,
        description="Raw perception evidence, consensus scoring, and uncertainties.",
    )
    quality_report: dict = Field(
        default_factory=dict,
        description="Automated rubric scoring + critique notes for iterative improvement.",
    )
    enhanced_assets: List[str] = Field(
        default_factory=list,
        description="URIs for enhanced images stored in object storage.",
    )
