# Generated by Django 5.2.11 on 2026-02-24 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveIntegerField(default=80001)),
                ('token_address', models.CharField(max_length=42)),
                ('wager_amount', models.BigIntegerField(help_text='Token amount in smallest units (e.g., USDC=6 decimals)')),
                ('player1_address', models.CharField(max_length=42)),
                ('player2_address', models.CharField(blank=True, max_length=42, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('contract_game_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'chain_id', 'token_address', 'wager_amount', 'created_at'], name='lobby_room_status_96ed8e_idx')],
            },
        ),
    ]
